import os
from datetime import datetime, timedelta, timezone

import pytest
from aiogram.fsm.state import State
from aiogram.fsm.storage.base import StorageKey
from aiogram.fsm.storage.redis import RedisStorage
from sqlalchemy import func, select

from foxgen.application.submissions import request_fingerprint
from foxgen.domain.models import GenerationStatus, MediaKind
from foxgen.infra.billing import SqlAlchemyBillingRepository
from foxgen.infra.billing_models import BalanceReservation, LedgerEntry
from foxgen.infra.database import Database, Generation, OutboxEvent
from foxgen.infra.lifecycle_repository import SqlAlchemyLifecycleRepository
from foxgen.infra.redis import RedisPool
from foxgen.infra.repositories import SqlAlchemyGenerationRepository


pytestmark = pytest.mark.skipif(
    os.getenv("FOXGEN_RUN_INTEGRATION") != "1",
    reason="real infrastructure tests are enabled only in the CI infrastructure job",
)


@pytest.mark.asyncio
async def test_atomic_admission_reserves_balance_and_writes_one_outbox() -> None:
    database = Database(os.environ["FOXGEN_DATABASE_URL"])
    billing = SqlAlchemyBillingRepository(database)
    generations = SqlAlchemyGenerationRepository(database)
    user_id = 910_000_001
    model_slug = "seedream-5-pro"
    idempotency_key = "integration-generation-0001"
    input_payload: dict[str, object] = {
        "prompt": "A fox generated by the infrastructure test",
        "aspect_ratio": "1:1",
        "quality": "basic",
        "output_format": "png",
        "nsfw_checker": False,
    }
    request_hash = request_fingerprint(
        model_slug=model_slug,
        input_payload=input_payload,
    )

    try:
        await billing.set_model_price(
            model_slug=model_slug,
            amount_units=250,
            currency="CREDIT",
            active_from=datetime.now(timezone.utc) - timedelta(minutes=1),
            active_until=None,
            metadata={"source": "integration-test"},
        )
        await billing.adjust_balance(
            user_id=user_id,
            username="integration-user",
            amount_units=1_000,
            idempotency_key="integration-credit-0001",
            actor="test:ci",
            reason="Fund infrastructure integration test",
        )

        first, created = await generations.admit(
            user_id=user_id,
            username="integration-user",
            idempotency_key=idempotency_key,
            request_hash=request_hash,
            model_slug=model_slug,
            media_kind=MediaKind.IMAGE,
            prompt=str(input_payload["prompt"]),
            input_payload=input_payload,
            user_concurrency_limit=2,
            global_concurrency_limit=20,
        )
        replay, replay_created = await generations.admit(
            user_id=user_id,
            username="integration-user",
            idempotency_key=idempotency_key,
            request_hash=request_hash,
            model_slug=model_slug,
            media_kind=MediaKind.IMAGE,
            prompt=str(input_payload["prompt"]),
            input_payload=input_payload,
            user_concurrency_limit=2,
            global_concurrency_limit=20,
        )

        assert created is True
        assert replay_created is False
        assert replay.id == first.id
        assert first.status == GenerationStatus.QUEUED

        balance = await billing.get_balance(user_id)
        assert balance.available_units == 750
        assert balance.reserved_units == 250

        async with database.session() as session:
            reservation_count = await session.scalar(
                select(func.count(BalanceReservation.id)).where(
                    BalanceReservation.generation_id == first.id
                )
            )
            reserve_ledger_count = await session.scalar(
                select(func.count(LedgerEntry.id)).where(
                    LedgerEntry.idempotency_key == f"reserve:{first.id}"
                )
            )
            outbox_count = await session.scalar(
                select(func.count(OutboxEvent.id)).where(
                    OutboxEvent.deduplication_key == f"generation.submit:{first.id}"
                )
            )
            generation_count = await session.scalar(
                select(func.count(Generation.id)).where(Generation.id == first.id)
            )

        assert reservation_count == 1
        assert reserve_ledger_count == 1
        assert outbox_count == 1
        assert generation_count == 1
    finally:
        await database.close()


@pytest.mark.asyncio
async def test_callback_inbox_is_deduplicated_in_real_postgres() -> None:
    database = Database(os.environ["FOXGEN_DATABASE_URL"])
    repository = SqlAlchemyLifecycleRepository(database)
    payload: dict[str, object] = {
        "taskId": "integration-provider-task-1",
        "state": "success",
        "resultJson": '{"resultUrls":["https://cdn.example/result.png"]}',
    }

    try:
        inserted = await repository.record_provider_event(
            provider="kie",
            provider_task_id="integration-provider-task-1",
            event_hash="f" * 64,
            payload=payload,
        )
        duplicate = await repository.record_provider_event(
            provider="kie",
            provider_task_id="integration-provider-task-1",
            event_hash="f" * 64,
            payload=payload,
        )

        assert inserted is True
        assert duplicate is False

        async with database.session() as session:
            callback_outbox_count = await session.scalar(
                select(func.count(OutboxEvent.id)).where(
                    OutboxEvent.deduplication_key == f"kie.callback:{'f' * 64}"
                )
            )
        assert callback_outbox_count == 1
    finally:
        await database.close()


@pytest.mark.asyncio
async def test_real_redis_supports_fsm_state_data_and_cleanup() -> None:
    redis_url = os.environ["FOXGEN_REDIS_URL"]
    pool = RedisPool(redis_url)
    storage = RedisStorage.from_url(redis_url, state_ttl=300, data_ttl=300)
    key = StorageKey(bot_id=1, chat_id=910_000_001, user_id=910_000_001)
    state = State("integration:waiting_prompt")

    try:
        await pool.ping()
        await storage.set_state(key, state)
        await storage.set_data(key, {"prompt": "integration fox", "step": 2})

        assert await storage.get_state(key) == state.state
        assert await storage.get_data(key) == {"prompt": "integration fox", "step": 2}

        await storage.set_state(key, None)
        await storage.set_data(key, {})
        assert await storage.get_state(key) is None
        assert await storage.get_data(key) == {}
    finally:
        await storage.close()
        await pool.close()
