import type { ImageModel, VideoModel, Task, AppState, ScenarioType, PaymentPackage } from './types'

export const mockPaymentPackages: PaymentPackage[] = [
  {
    id: 'mini',
    name: '🍌 Мини',
    credits: 15,
    price_rub: 150,
    description: 'Для пробы',
  },
  {
    id: 'start',
    name: '🍌 Старт',
    credits: 25,
    price_rub: 250,
    description: 'Удобный старт',
  },
  {
    id: 'optimal',
    name: '🍌🍌 Оптимальный',
    credits: 50,
    price_rub: 500,
    popular: true,
    description: 'Лучшее соотношение цена/количество',
  },
  {
    id: 'pro',
    name: '🍌🍌🍌 Про',
    credits: 100,
    price_rub: 1000,
    description: 'Для активных пользователей',
  },
  {
    id: 'studio',
    name: '🍌🍌🍌🍌 Студия',
    credits: 200,
    price_rub: 1950,
    description: 'Для частой генерации',
  },
  {
    id: 'business',
    name: '🍌🍌🍌🍌🍌 Бизнес',
    credits: 500,
    price_rub: 4900,
    description: 'Выгодно для регулярной работы',
  },
]

export const mockImageModels: ImageModel[] = [
  {
    id: 'nano-banana-2-lite',
    label: 'Nano Banana 2 Lite 🔥 НОВИНКА',
    description: 'Быстрая новинка для лёгких image-задач и быстрых итераций',
    cost: 1,
    ratios: [
      '1:1',
      '16:9',
      '9:16',
      '4:3',
      '3:4',
      '4:5',
      '5:4',
      '3:2',
      '2:3',
      '21:9',
    ],
    requires_reference: false,
    max_references: 14,
  },
  {
    id: 'seedream_5_pro',
    label: 'Seedream 5 Pro 🔥 НОВИНКА',
    description: 'Фотореалистичная генерация с нуля и image-to-image в одном режиме',
    cost: 2,
    ratios: ['1:1', '9:16', '16:9', '3:4', '4:3', '2:3', '3:2', '21:9'],
    requires_reference: false,
    max_references: 5,
    qualities: ['basic', 'high'],
    quality_costs: { basic: 2, high: 2.5 },
  },
  {
    id: 'banana_pro',
    label: 'Nano Banana Pro',
    description: 'Универсальная модель для качественных изображений',
    cost: 2.5,
    ratios: [
      '1:1',
      '16:9',
      '9:16',
      '4:3',
      '3:4',
      '4:5',
      '5:4',
      '3:2',
      '2:3',
      '21:9',
    ],
    requires_reference: false,
    max_references: 14,
    qualities: ['1K', '2K', '4K'],
    quality_costs: { '1K': 2.5, '2K': 2.5, '4K': 3.5 },
  },
  {
    id: 'banana_2',
    label: 'Nano Banana 2',
    description: 'Новая версия Nano Banana с улучшенной детализацией и цветопередачей',
    cost: 2.5,
    ratios: [
      '1:1',
      '16:9',
      '9:16',
      '4:3',
      '3:4',
      '4:5',
      '5:4',
      '3:2',
      '2:3',
      '21:9',
    ],
    requires_reference: false,
    max_references: 14,
    qualities: ['1K', '2K', '4K'],
    quality_costs: { '1K': 2.5, '2K': 2.5, '4K': 3.5 },
  },
  {
    id: 'seedream_edit',
    label: 'Seedream 4.5 Edit',
    description: 'Редактирование и стилизация существующих изображений',
    cost: 1.5,
    ratios: ['1:1', '9:16', '16:9', '3:4', '4:3', '2:3', '3:2', '21:9'],
    requires_reference: true,
    max_references: 14,
    qualities: ['2K', '4K'],
    supports_nsfw_checker: true,
  },
  {
    id: 'flux_pro',
    label: 'GPT Image 2',
    description: 'Передовая модель с поддержкой авто-формата',
    cost: 2,
    ratios: ['auto', '1:1', '9:16', '16:9', '3:4', '4:3', '2:3'],
    requires_reference: false,
    max_references: 16,
    supports_nsfw_checker: true,
  },
  {
    id: 'grok_imagine_i2i',
    label: 'Grok Imagine',
    description: 'Креативная генерация с уникальным стилем',
    cost: 3,
    ratios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    requires_reference: true,
    max_references: 7,
    supports_nsfw_mode: true,
  },
]

export const mockVideoModels: VideoModel[] = [
  {
    id: 'v3_pro',
    label: 'Kling 3.0',
    description: 'Новейшая версия с улучшенным качеством движения',
    durations: [5, 10, 15],
    ratios: ['1:1', '9:16', '16:9'],
    supports: ['text', 'imgtxt', 'video'] as ScenarioType[],
    costs: { '5': 15, '10': 30, '15': 45 },
    max_image_references: 12,
    max_video_references: 5,
  },
  {
    id: 'v3_std',
    label: 'Kling v3',
    description: 'Стабильная версия для профессионального контента',
    durations: [5, 10, 15],
    ratios: ['1:1', '9:16', '16:9'],
    supports: ['text', 'imgtxt', 'video'] as ScenarioType[],
    costs: { '5': 15, '10': 30, '15': 45 },
    max_image_references: 12,
    max_video_references: 5,
  },
  {
    id: 'v26_pro',
    label: 'Kling 2.5 Turbo Pro',
    description: 'Быстрая генерация с хорошим качеством',
    durations: [5, 10],
    ratios: ['1:1', '9:16', '16:9'],
    supports: ['text', 'imgtxt'] as ScenarioType[],
    costs: { '5': 15, '10': 30 },
    supports_negative_prompt: true,
    supports_cfg_scale: true,
    max_image_references: 12,
  },
  {
    id: 'grok_imagine',
    label: 'Grok Imagine',
    description: 'Уникальный стиль генерации видео',
    durations: [6, 10, 20, 30],
    ratios: ['1:1', '16:9', '9:16', '3:2', '2:3'],
    supports: ['imgtxt'] as ScenarioType[],
    costs: { '6': 9, '10': 15, '20': 30, '30': 45 },
    grok_modes: ['normal', 'fun', 'spicy'],
    max_image_references: 6,
  },
  {
    id: 'veo3_fast',
    label: 'Veo 3.1 Fast',
    description: 'Сверхбыстрая генерация от Google',
    durations: [5, 8],
    ratios: ['9:16', '16:9', 'Auto'],
    supports: ['text', 'imgtxt'] as ScenarioType[],
    costs: { '5': 15, '8': 15 },
    veo_generation_types: ['TEXT_2_VIDEO', 'FIRST_AND_LAST_FRAMES_2_VIDEO', 'REFERENCE_2_VIDEO'],
    veo_resolutions: ['720p'],
    supports_translation: true,
    supports_seed: true,
    supports_watermark: true,
    max_image_references: 3,
  },
  {
    id: 'motion_control_v26',
    label: 'Kling 2.6 Motion Control',
    description: 'Перенос движения с видео на фото персонажа',
    durations: [5],
    ratios: ['motion'],
    supports: ['video'] as ScenarioType[],
    costs: { '5': 10 },
    quality_costs: { '720p': 10, '1080p': 15 },
    max_image_references: 1,
    max_video_references: 1,
  },
  {
    id: 'motion_control_v30',
    label: 'Kling 3.0 Motion Control',
    description: 'Обновлённая motion-модель для переноса движения',
    durations: [5],
    ratios: ['motion'],
    supports: ['video'] as ScenarioType[],
    costs: { '5': 15 },
    quality_costs: { '720p': 15, '1080p': 20 },
    max_image_references: 1,
    max_video_references: 1,
  },
]

export const mockTasks: Task[] = [
  {
    task_id: 'task_demo_001',
    type: 'image',
    model: 'banana_pro',
    model_label: 'Nano Banana Pro',
    aspect_ratio: '1:1',
    status: 'completed',
    result_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800',
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    prompt_preview: 'Футуристический город на закате с неоновыми огнями...',
    cost: 2,
  },
  {
    task_id: 'task_demo_002',
    type: 'video',
    model: 'v3_pro',
    model_label: 'Kling 3.0',
    aspect_ratio: '16:9',
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    prompt_preview: 'Плавное движение камеры через туманный лес...',
    cost: 8,
    duration: 5,
  },
  {
    task_id: 'task_demo_003',
    type: 'image',
    model: 'flux_pro',
    model_label: 'GPT Image 2',
    aspect_ratio: '9:16',
    status: 'completed',
    result_url: 'https://images.unsplash.com/photo-1634017839464-5c339bbe3c7f?w=800',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    prompt_preview: 'Минималистичный портрет в стиле editorial fashion...',
    cost: 4,
  },
  {
    task_id: 'task_demo_004',
    type: 'video',
    model: 'veo3_fast',
    model_label: 'Veo 3.1 Fast',
    aspect_ratio: '9:16',
    status: 'failed',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    prompt_preview: 'Танцующие частицы света в абстрактном пространстве...',
    cost: 5,
    duration: 5,
  },
  {
    task_id: 'task_demo_005',
    type: 'image',
    model: 'seedream_edit',
    model_label: 'Seedream 4.5 Edit',
    aspect_ratio: '3:4',
    status: 'completed',
    result_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    prompt_preview: 'Стилизация под импрессионизм с мягкими мазками...',
    cost: 3,
  },
]

export const mockAppState: AppState = {
  mode: 'locked',
  isLoading: false,
  error: null,
  user: {
    telegramId: 100001,
    firstName: 'Пользователь',
    lastName: '',
    username: 'banana_creator',
    photoUrl: '',
    referralCode: 'DEMO2026',
    profileLink: 'https://t.me/BananaBoombot_bot?start=posts_DEMO2026_ref_DEMO2026',
    referralLink: 'https://t.me/BananaBoombot_bot?start=ref_DEMO2026',
    channelUrl: 'https://t.me/banana_creator',
    promptRepeatBalanceRub: 120,
    promptRepeatTotalRub: 340,
    botUsername: 'BananaBoombot_bot',
    credits: 5,
    isAdmin: false,
  },
  imageModels: mockImageModels,
  videoModels: mockVideoModels,
  recentTasks: mockTasks,
  savedReferences: [],
  paymentPackages: mockPaymentPackages,
  lastSync: new Date(),
}

export const mockTaskDetails: Record<string, {
  prompt: string
  request_data?: {
    reference_images?: string[]
    v_reference_videos?: string[]
  }
}> = {
  'task_demo_001': {
    prompt: 'Футуристический город на закате с неоновыми огнями, киберпанк эстетика, высокие небоскрёбы отражаются в воде, тёплые оранжевые и холодные голубые тона, кинематографическое освещение, 8k качество',
  },
  'task_demo_002': {
    prompt: 'Плавное движение камеры через туманный лес на рассвете, солнечные лучи пробиваются сквозь листву, мистическая атмосфера, cinematic, slow motion, высокая детализация',
  },
  'task_demo_003': {
    prompt: 'Минималистичный портрет в стиле editorial fashion, мягкое студийное освещение, нейтральный фон, профессиональная модель, высокая чёткость, журнальное качество',
    request_data: {
      reference_images: ['https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400'],
    },
  },
  'task_demo_004': {
    prompt: 'Танцующие частицы света в абстрактном пространстве, плавные переливы цветов, магическая атмосфера, loop-friendly, высокое разрешение',
  },
  'task_demo_005': {
    prompt: 'Стилизация под импрессионизм с мягкими мазками кисти, пастельная палитра, атмосфера французской живописи 19 века, художественная обработка',
    request_data: {
      reference_images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400'],
    },
  },
}
