#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
import sqlite3
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def qident(name: str) -> str:
    if IDENT_RE.match(name):
        return f'"{name}"'
    return '"' + name.replace('"', '""') + '"'


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def sqlite_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [row[0] for row in rows]


def table_columns(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    rows = conn.execute(f"PRAGMA table_info({qident(table)})").fetchall()
    return [
        {
            'cid': row[0],
            'name': row[1],
            'type': row[2] or 'TEXT',
            'notnull': bool(row[3]),
            'default': row[4],
            'pk': int(row[5]),
        }
        for row in rows
    ]


def table_foreign_keys(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    rows = conn.execute(f"PRAGMA foreign_key_list({qident(table)})").fetchall()
    grouped: dict[int, dict[str, Any]] = {}
    for row in rows:
        item = grouped.setdefault(
            int(row[0]),
            {
                'id': int(row[0]),
                'table': row[2],
                'from': [],
                'to': [],
                'on_update': row[5],
                'on_delete': row[6],
            },
        )
        item['from'].append(row[3])
        item['to'].append(row[4])
    return list(grouped.values())


def table_indexes(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    result = []
    for idx in conn.execute(f"PRAGMA index_list({qident(table)})").fetchall():
        idx_name = idx[1]
        unique = bool(idx[2])
        origin = idx[3]
        partial = bool(idx[4]) if len(idx) > 4 else False
        if origin == 'pk' or partial:
            continue
        cols = [r[2] for r in conn.execute(f"PRAGMA index_info({qident(idx_name)})").fetchall()]
        result.append({'name': idx_name, 'unique': unique, 'columns': cols})
    return result


def map_type(sqlite_type: str) -> str:
    t = (sqlite_type or '').upper()
    if 'INT' in t:
        return 'BIGINT'
    if any(x in t for x in ('CHAR', 'CLOB', 'TEXT')):
        return 'TEXT'
    if 'BLOB' in t:
        return 'BYTEA'
    if any(x in t for x in ('REAL', 'FLOA', 'DOUB')):
        return 'DOUBLE PRECISION'
    if 'BOOL' in t:
        return 'BOOLEAN'
    if 'DATE' in t or 'TIME' in t:
        return 'TIMESTAMP'
    if 'NUM' in t or 'DEC' in t:
        return 'NUMERIC'
    return 'TEXT'


def map_default(value: Any, pg_type: str) -> str | None:
    if value is None:
        return None
    raw = str(value).strip()
    if not raw:
        return None
    upper = raw.upper()
    if upper in {'CURRENT_TIMESTAMP', '(CURRENT_TIMESTAMP)'}:
        return 'CURRENT_TIMESTAMP'
    if pg_type == 'BOOLEAN' and raw in {'0', '1'}:
        return 'FALSE' if raw == '0' else 'TRUE'
    if re.fullmatch(r'-?\d+(\.\d+)?', raw):
        return raw
    if raw.startswith("'") and raw.endswith("'"):
        return raw
    return "'" + raw.replace("'", "''") + "'"


def create_table_sql(conn: sqlite3.Connection, table: str) -> tuple[str, str | None, list[str]]:
    cols = table_columns(conn, table)
    fks = table_foreign_keys(conn, table)
    pk_cols = [c for c in sorted(cols, key=lambda x: x['pk']) if c['pk']]
    single_int_pk = len(pk_cols) == 1 and 'INT' in (pk_cols[0]['type'] or '').upper()
    identity_col = pk_cols[0]['name'] if single_int_pk else None

    col_defs: list[str] = []
    for col in cols:
        pg_type = map_type(col['type'])
        pieces = [qident(col['name'])]
        if single_int_pk and col['name'] == identity_col:
            pieces.append('BIGINT GENERATED BY DEFAULT AS IDENTITY')
            pieces.append('PRIMARY KEY')
        else:
            pieces.append(pg_type)
            default = map_default(col['default'], pg_type)
            if default is not None:
                pieces.append(f'DEFAULT {default}')
            if col['notnull']:
                pieces.append('NOT NULL')
        col_defs.append(' '.join(pieces))

    constraints: list[str] = []
    if pk_cols and not single_int_pk:
        constraints.append(
            'PRIMARY KEY (' + ', '.join(qident(c['name']) for c in pk_cols) + ')'
        )

    fk_statements: list[str] = []
    for fk in fks:
        cname = f'{table}_fk_{fk["id"]}'
        clause = (
            f'ALTER TABLE {qident(table)} ADD CONSTRAINT {qident(cname)} FOREIGN KEY ('
            + ', '.join(qident(c) for c in fk['from'])
            + ') REFERENCES '
            + qident(fk['table'])
            + ' ('
            + ', '.join(qident(c) for c in fk['to'])
            + ')'
        )
        if fk['on_delete'] and fk['on_delete'].upper() != 'NO ACTION':
            clause += f' ON DELETE {fk["on_delete"]}'
        if fk['on_update'] and fk['on_update'].upper() != 'NO ACTION':
            clause += f' ON UPDATE {fk["on_update"]}'
        fk_statements.append(clause)

    body = ',\n    '.join(col_defs + constraints)
    return f'CREATE TABLE IF NOT EXISTS {qident(table)} (\n    {body}\n);', identity_col, fk_statements


def drop_public_tables(pg: psycopg.Connection) -> None:
    with pg.cursor() as cur:
        cur.execute("SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename")
        for (table,) in cur.fetchall():
            cur.execute(sql.SQL('DROP TABLE IF EXISTS {} CASCADE').format(sql.Identifier(table)))
    pg.commit()


def create_schema(sqlite_conn: sqlite3.Connection, pg: psycopg.Connection, tables: list[str]) -> tuple[dict[str, str | None], list[str]]:
    identity_cols: dict[str, str | None] = {}
    fk_statements: list[str] = []
    with pg.cursor() as cur:
        for table in tables:
            ddl, identity_col, table_fk_statements = create_table_sql(sqlite_conn, table)
            cur.execute(ddl)
            identity_cols[table] = identity_col
            fk_statements.extend(table_fk_statements)
    pg.commit()

    with pg.cursor() as cur:
        for table in tables:
            for idx in table_indexes(sqlite_conn, table):
                idx_name = idx['name']
                cols = ', '.join(qident(col) for col in idx['columns'])
                unique = 'UNIQUE ' if idx['unique'] else ''
                cur.execute(f'CREATE {unique}INDEX IF NOT EXISTS {qident(idx_name)} ON {qident(table)} ({cols})')
    pg.commit()
    return identity_cols, fk_statements


def apply_foreign_keys(pg: psycopg.Connection, fk_statements: list[str]) -> None:
    with pg.cursor() as cur:
        for stmt in fk_statements:
            cur.execute(stmt)
    pg.commit()


def normalize_value(value: Any, pg_type: str) -> Any:
    if value is None:
        return None
    if pg_type == 'BOOLEAN':
        if isinstance(value, bool):
            return value
        if isinstance(value, (int, float)):
            return bool(value)
        sval = str(value).strip().lower()
        if sval in {'1', 'true', 't', 'yes'}:
            return True
        if sval in {'0', 'false', 'f', 'no'}:
            return False
    return value


def migrate_data(sqlite_conn: sqlite3.Connection, pg: psycopg.Connection, tables: list[str], identity_cols: dict[str, str | None], batch_size: int) -> dict[str, int]:
    counts: dict[str, int] = {}
    for table in tables:
        cols = table_columns(sqlite_conn, table)
        col_names = [c['name'] for c in cols]
        pg_types = [map_type(c['type']) for c in cols]
        select_sql = f'SELECT {", ".join(qident(c) for c in col_names)} FROM {qident(table)}'
        rows = sqlite_conn.execute(select_sql)
        placeholders = ', '.join(['%s'] * len(col_names))
        insert_sql = f'INSERT INTO {qident(table)} ({", ".join(qident(c) for c in col_names)}) VALUES ({placeholders})'
        moved = 0
        with pg.cursor() as cur:
            batch = []
            for row in rows:
                batch.append(tuple(normalize_value(v, pg_types[i]) for i, v in enumerate(row)))
                if len(batch) >= batch_size:
                    cur.executemany(insert_sql, batch)
                    moved += len(batch)
                    batch.clear()
            if batch:
                cur.executemany(insert_sql, batch)
                moved += len(batch)
        pg.commit()
        identity_col = identity_cols.get(table)
        if identity_col:
            with pg.cursor() as cur:
                cur.execute(
                    f"SELECT setval(pg_get_serial_sequence('{table}', '{identity_col}'), COALESCE((SELECT MAX({qident(identity_col)}) FROM {qident(table)}), 1), true)"
                )
            pg.commit()
        counts[table] = moved
        print(f'[migrate] {table}: {moved} rows')
    return counts


def verify_counts(sqlite_conn: sqlite3.Connection, pg: psycopg.Connection, tables: list[str]) -> list[str]:
    mismatches = []
    with pg.cursor(row_factory=dict_row) as cur:
        for table in tables:
            sqlite_count = sqlite_conn.execute(f'SELECT COUNT(*) FROM {qident(table)}').fetchone()[0]
            cur.execute(sql.SQL('SELECT COUNT(*) AS count FROM {}').format(sql.Identifier(table)))
            pg_count = cur.fetchone()['count']
            status = 'OK' if sqlite_count == pg_count else 'MISMATCH'
            print(f'[verify] {table}: sqlite={sqlite_count} postgres={pg_count} -> {status}')
            if sqlite_count != pg_count:
                mismatches.append(table)
    return mismatches


def main() -> int:
    parser = argparse.ArgumentParser(description='Migrate banano_kling SQLite DB to PostgreSQL')
    parser.add_argument('--sqlite-path', default='bot.db')
    parser.add_argument('--pg-dsn', default='')
    parser.add_argument('--drop-existing', action='store_true')
    parser.add_argument('--batch-size', type=int, default=1000)
    args = parser.parse_args()

    project_dir = Path(__file__).resolve().parents[1]
    load_env_file(project_dir / '.env.postgres')
    if not args.pg_dsn:
        args.pg_dsn = os.getenv('DATABASE_URL', '')
    if not args.pg_dsn.startswith(('postgresql://', 'postgres://')):
        raise SystemExit('PostgreSQL DATABASE_URL is required (use .env.postgres or --pg-dsn)')

    sqlite_path = Path(args.sqlite_path)
    if not sqlite_path.is_absolute():
        sqlite_path = project_dir / sqlite_path
    if not sqlite_path.exists():
        raise SystemExit(f'SQLite DB not found: {sqlite_path}')

    sqlite_conn = sqlite3.connect(sqlite_path)
    sqlite_conn.row_factory = sqlite3.Row
    sqlite_conn.execute('PRAGMA foreign_keys=OFF')
    tables = sqlite_tables(sqlite_conn)
    print('[info] tables:', ', '.join(tables))

    with psycopg.connect(args.pg_dsn, autocommit=False) as pg:
        if args.drop_existing:
            drop_public_tables(pg)
        identity_cols, fk_statements = create_schema(sqlite_conn, pg, tables)
        migrate_data(sqlite_conn, pg, tables, identity_cols, max(1, args.batch_size))
        apply_foreign_keys(pg, fk_statements)
        mismatches = verify_counts(sqlite_conn, pg, tables)

    sqlite_conn.close()
    if mismatches:
        print('[result] mismatches:', ', '.join(mismatches))
        return 1
    print('[result] migration verified successfully')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
