#! /usr/bin/env bash
# Helper: download Cloudflare IP lists and write /etc/nginx/cloudflare.conf
# Run with sudo: sudo bash scripts/update_cloudflare_conf.sh

set -euo pipefail

CF_V4_URL="https://www.cloudflare.com/ips-v4"
CF_V6_URL="https://www.cloudflare.com/ips-v6"
OUT_FILE="/etc/nginx/cloudflare.conf"

tmpf=$(mktemp)
trap 'rm -f "$tmpf"' EXIT

echo "# This file is autogenerated by scripts/update_cloudflare_conf.sh" > "$tmpf"
echo "# Do not edit manually; re-run the script to update Cloudflare ranges." >> "$tmpf"
echo >> "$tmpf"

echo "# IPv4 ranges" >> "$tmpf"
curl -fsS "$CF_V4_URL" | while read -r ip; do
  echo "set_real_ip_from $ip;" >> "$tmpf"
done

echo >> "$tmpf"
echo "# IPv6 ranges" >> "$tmpf"
curl -fsS "$CF_V6_URL" | while read -r ip; do
  echo "set_real_ip_from $ip;" >> "$tmpf"
done

cat >> "$tmpf" <<'EOF'
real_ip_header CF-Connecting-IP;
real_ip_recursive on;
EOF

echo "Writing $OUT_FILE (backup existing file if present)"
if [ -f "$OUT_FILE" ]; then
  cp -a "$OUT_FILE" "$OUT_FILE.bak.$(date +%s)" && echo "Backup saved to $OUT_FILE.bak.*"
fi

sudo install -m 0644 "$tmpf" "$OUT_FILE"

echo "Reloading nginx to apply new config"
sudo nginx -t && sudo systemctl reload nginx

echo "Done."
